export const GET_PRODUCT_REQUEST = `GET_PRODUCT_REQUEST`;
export const GET_PRODUCT_SUCCESS = `GET_PRODUCT_SUCCESS`;
export const GET_PRODUCT_FAILURE = `GET_PRODUCT_FAILURE`;

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREV_PAGE = "SET_PREV_PAGE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const GET_RANDOM_PRODUCTS = "GET_RANDOM_PRODUCTS";
export const GET_STATE_PRODUCTS = "GET_STATE_PRODUCTS";

export const SET_STATE_PRODUCTS_NULL = "SET_STATE_PRODUCTS_NULL";

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";

export const GET_CURRENT_PRODUCT_STATE_DETAILS =
  "GET_CURRENT_PRODUCT_STATE_DETAILS";
